# Generated by Django 5.1.3 on 2024-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0003_remove_product_explanation_remove_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, default="noImage.png", upload_to=""),
        ),
    ]
